### ISSUE TITLE
MarkdowneditorConverter returns empty object

### ISSUE THREAD

**Issue by WayneKruger** [deMD/UmbracoContentApi#23]
Firstly thank you for this library, you saved me so much work!

Your MarkdowneditorConverter returns an empty object 

`{
    "markdown": {}
}`

The value passed to the Convert method is of type System.Web.HtmlString so as a workaround I just replaced the converter with my own where I return value.ToHtmlString() but you might want to update your convert to do this by default

**Comment by deMD** [comment]
Fixed in #24
