### ISSUE TITLE
No converter implemented for editor: Umbraco.Grid

### ISSUE THREAD

**Issue by cdecinkoKnight** [deMD/UmbracoContentApi#4]
Not sure if we would use the grid to manage content to be used outside of Umbraco but would be a nice feature to at least reference how to dig in via the API to get this content.

**Comment by deMD** [comment]
The grid has not been implemented due to it's structured nature. As this package is meant for providing content api's, I made the decision to not create my own implementation of a grid converter.

If you want to use the grid in your api, you can create your own converter as described in the readme.
