### ISSUE TITLE
Resolving images in grid rte not supported?

### ISSUE THREAD

**Issue by jesperordrup** [deMD/UmbracoContentApi#41]
Im resolving the content like this:

    var contentResolved = _contentResolver.Value.ResolveContent( content, dictionary);

Do I need to do anything else?

The result is:

![image](https://user-images.githubusercontent.com/3120151/158998602-23a658ef-0a36-477b-8784-a8f017947b46.png)

Umbraco 8.18
UmbracoContentApi.Core -Version 4.0.1

**Comment by jesperordrup** [comment]
Found the reason. Its not implemented 😄 

Here's a suggestion:

    public class RteConverter : IGridConverter
    {
        private readonly IUmbracoContextFactory _umbracoContextFactory;
        private readonly HtmlLocalLinkParser _localLinkParser;
        private readonly HtmlImageSourceParser _localImageParser;


        public RteConverter(IUmbracoContextFactory umbracoContextFactory, HtmlLocalLinkParser localLinkParser, HtmlImageSourceParser localImageParser)
        {
            _umbracoContextFactory = umbracoContextFactory;
            _localLinkParser = localLinkParser;
            _localImageParser = localImageParser;
        }

        public string EditorAlias => "rte";

        public object Convert(object value)
        {
            using (var cRef = _umbracoContextFactory.EnsureUmbracoContext())
            {
                var parsedHtml = _localLinkParser.EnsureInternalLinks(value.ToString(), false);
                parsedHtml = _localImageParser.EnsureImageSources(parsedHtml);
                return parsedHtml;
            }
        }
    }

**Comment by jesperordrup** [comment]
See pull request

**Comment by deMD** [comment]
Solved in #42
